In [1]:
import numpy as np
import pandas as pd
import ast
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [5]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [6]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

# Merging two dataset with Title

In [7]:
movies = movies.merge(credits, on= "title")
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
 movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

# Removing unwanted columns from dataset

In [9]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

In [10]:
col = ["movie_id", 'title', "genres", 'keywords','overview', 'cast','crew']

In [11]:
movies = movies[col]
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [12]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [13]:
movies =movies.dropna()

In [14]:
def genre(text):
    Genre = []
    for i in ast.literal_eval(text):
        Genre.append(i['name'])
    return Genre

In [15]:
movies['genres'] = movies['genres'].apply(genre)
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,[Documentary],"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [16]:
movies['keywords'] = movies['keywords'].apply(genre)
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [17]:
movies['cast'][1]

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [18]:
def cast(text):
    c = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter <3:
            c.append(i['name'])
            counter +=1
    return c

In [19]:
movies['cast'] = movies['cast'].apply(cast)
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [20]:
movies['crew'][1]

'[{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photography", "name": "Dariusz Wolski"}, {"credit_id": "52fe4232c3a36847f800b4fd", "department": "Directing", "gender": 2, "id": 1704, "job": "Director", "name": "Gore Verbinski"}, {"credit_id": "52fe4232c3a36847f800b54f", "department": "Production", "gender": 2, "id": 770, "job": "Producer", "name": "Jerry Bruckheimer"}, {"credit_id": "52fe4232c3a36847f800b503", "department": "Writing", "gender": 2, "id": 1705, "job": "Screenplay", "name": "Ted Elliott"}, {"credit_id": "52fe4232c3a36847f800b509", "department": "Writing", "gender": 2, "id": 1706, "job": "Screenplay", "name": "Terry Rossio"}, {"credit_id": "52fe4232c3a36847f800b57f", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "52fe4232c3a36847f800b585", "department": "Editing", "gender": 2, "id": 1722, "job": "Editor", "name": "Craig Wood"}, {"credit_id": "52fe4232c3a36847f800b573", "department": "Sound", "gender": 2, "id": 947, "job": "Original Music Composer", "name": "Hans Zimmer"}, {"credit_id": "52fe4232c3a36847f800b555", "department": "Production", "gender": 2, "id": 2444, "job": "Executive Producer", "name": "Mike Stenson"}, {"credit_id": "52fe4232c3a36847f800b561", "department": "Production", "gender": 2, "id": 2445, "job": "Producer", "name": "Eric McLeod"}, {"credit_id": "52fe4232c3a36847f800b55b", "department": "Production", "gender": 2, "id": 2446, "job": "Producer", "name": "Chad Oman"}, {"credit_id": "52fe4232c3a36847f800b567", "department": "Production", "gender": 0, "id": 2447, "job": "Producer", "name": "Peter Kohn"}, {"credit_id": "52fe4232c3a36847f800b56d", "department": "Production", "gender": 0, "id": 2448, "job": "Producer", "name": "Pat Sandston"}, {"credit_id": "52fe4232c3a36847f800b58b", "department": "Production", "gender": 1, "id": 2215, "job": "Casting", "name": "Denise Chamian"}, {"credit_id": "52fe4232c3a36847f800b597", "department": "Art", "gender": 2, "id": 1226, "job": "Production Design", "name": "Rick Heinrichs"}, {"credit_id": "52fe4232c3a36847f800b59d", "department": "Art", "gender": 2, "id": 553, "job": "Art Direction", "name": "John Dexter"}, {"credit_id": "52fe4232c3a36847f800b591", "department": "Production", "gender": 1, "id": 3311, "job": "Casting", "name": "Priscilla John"}, {"credit_id": "52fe4232c3a36847f800b5a3", "department": "Art", "gender": 1, "id": 4032, "job": "Set Decoration", "name": "Cheryl Carasik"}, {"credit_id": "52fe4232c3a36847f800b5a9", "department": "Costume & Make-Up", "gender": 0, "id": 4033, "job": "Costume Design", "name": "Liz Dann"}, {"credit_id": "52fe4232c3a36847f800b5af", "department": "Costume & Make-Up", "gender": 1, "id": 4034, "job": "Costume Design", "name": "Penny Rose"}, {"credit_id": "56427ce8c3a3686a53000d8b", "department": "Sound", "gender": 2, "id": 5132, "job": "Music Supervisor", "name": "Bob Badami"}, {"credit_id": "55993c15c3a36855db002f33", "department": "Art", "gender": 2, "id": 146439, "job": "Conceptual Design", "name": "James Ward Byrkit"}, {"credit_id": "52fe4232c3a36847f800b5b9", "department": "Costume & Make-Up", "gender": 1, "id": 406204, "job": "Makeup Department Head", "name": "Ve Neill"}, {"credit_id": "56e47f7892514132690017bd", "department": "Crew", "gender": 2, "id": 1259516, "job": "Stunts", "name": "John Dixon"}, {"credit_id": "5740be639251416597000849", "department": "Crew", "gender": 0, "id": 1336716, "job": "CGI Supervisor", "name": "Dottie Starling"}, {"credit_id": "56427c639251412fc8000dc1", "department": "Directing", "gender": 1, "id": 1344278, "job": "Script Supervisor", "name": "Pamela Alch"}, {"credit_id": "57083101c3a3681d320004e6", "department": "Crew", "gender": 0, "id": 1368867, "job": "Special Effects Coordinator", "name": "Allen Hall"}, {"credit_id": "56427d5ec3a3686a62000d4a", "department": "Sound", "gender": 0, "id": 1368884, "job": "Music Editor", "name": "Melissa Muik"}, {"credit_id": "56427c7b9251412fd4000e07", "department": "Directing", "gender": 1, "id": 1395290, "job": "Script Supervisor", "name": "Sharron Reynolds"}, {"credit_id": "56427d2bc3a3686a53000d9b", "department": "Sound", "gender": 0, "id": 1399327, "job": "Music Editor", "name": "Barbara McDermott"}, {"credit_id": "56427cb4c3a3686a53000d87", "department": "Directing", "gender": 1, "id": 1400738, "job": "Script Supervisor", "name": "Karen Golden"}, {"credit_id": "56427d169251412fd4000e23", "department": "Sound", "gender": 0, "id": 1534197, "job": "Music Editor", "name": "Katie Greathouse"}]'

In [21]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [22]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[united statesâ€“mexico barrier, legs, arms, pap...",El Mariachi just wants to play his guitar and ...,"[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,72766,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[Edward Burns, Kerry BishÃ©, Marsha Dietlein]",[Edward Burns]
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investi...","""Signed, Sealed, Delivered"" introduces a dedic...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,25975,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]",Ever since the second grade when he first saw ...,"[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]"

Here we have a problelm in all columns. exalmple "Science Fiction" is complete on word but due to space in between that i consider as to different words. So we Need to remove spaces in between the words in the columns.

#  Removing Space gaps in columns

In [23]:
def Removing_spaces(text):
    text1 = []
    for i in text:
        text1.append(i.replace(' ', ''))
    return text1

In [24]:
movies.columns

Index(['movie_id', 'title', 'genres', 'keywords', 'overview', 'cast', 'crew'], dtype='object')

In [25]:
movies['keywords'] =movies['keywords'].apply(Removing_spaces)
movies['cast'] =movies['cast'].apply(Removing_spaces)
movies['crew'] =movies['crew'].apply(Removing_spaces)
movies

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bondâ€™s past sends him o...,"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,"[Action, Crime, Thriller]","[unitedstatesâ€“mexicobarrier, legs, arms, paper...",El Mariachi just wants to play his guitar and ...,"[CarlosGallardo, JaimedeHoyos, PeterMarquardt]",[RobertRodriguez]
4805,72766,Newlyweds,"[Comedy, Romance]",[],A newlywed couple's honeymoon is upended by th...,"[EdwardBurns, KerryBishÃ©, MarshaDietlein]",[EdwardBurns]
4806,231617,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, loveatfirstsight, narration, investigat...","""Signed, Sealed, Delivered"" introduces a dedic...","[EricMabius, KristinBooth, CrystalLowe]",[ScottSmith]
4807,126186,Shanghai Calling,[],[],When ambitious New York attorney Sam is sent t...,"[DanielHenney, ElizaCoupe, BillPaxton]",[DanielHsia]
4808,25975,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dreamgirl]",Ever since the second grade when he first saw ...,"[DrewBarrymore, BrianHerzlinger, CoreyFeldman]","[BrianHerzlinger, JonGunn, BrettWinn]"

In [26]:
movies['overview']= movies['overview'].apply(lambda x: x.split())

movies.head()

,movie_id,title,genres,keywords,overview,cast,crew
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [27]:
movies['overview'][1]

['Captain',
 'Barbossa,',
 'long',
 'believed',
 'to',
 'be',
 'dead,',
 'has',
 'come',
 'back',
 'to',
 'life',
 'and',
 'is',
 'headed',
 'to',
 'the',
 'edge',
 'of',
 'the',
 'Earth',
 'with',
 'Will',
 'Turner',
 'and',
 'Elizabeth',
 'Swann.',
 'But',
 'nothing',
 'is',
 'quite',
 'as',
 'it',
 'seems.']

In [28]:
movies.columns

Index(['movie_id', 'title', 'genres', 'keywords', 'overview', 'cast', 'crew'], dtype='object')

In [29]:
movies['tags'] = movies["genres"]+movies["keywords"]+movies["overview"]+movies['cast']+movies['crew']
movies.head()

,movie_id,title,genres,keywords,overview,cast,crew,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[Action, Adventure, Science Fiction, basedonno..."

In [30]:
new_movies = movies[['movie_id', 'title', "tags"]]
new_movies.head()

,movie_id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, Science Fiction, basedonno..."

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [32]:

def stem(text):
    y = []
    for word in text:  # Assuming text is a list of words
        y.append(ps.stem(word))
    return " ".join(y)  # Join the stemmed words back into a single string

# Apply the stem function to each element in the 'tags' column
new_movies['tags'] = new_movies['tags'].apply(stem)

In [33]:
new_movies['tags'][0]

'action adventur fantasi science fict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. samworthington zoesaldana sigourneyweav jamescameron'

In [34]:

cv = CountVectorizer(max_features= 5000, stop_words = 'english')
vectors = cv.fit_transform(new_movies['tags']).toarray()
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(vectors)

In [37]:
sorted(list(enumerate(similarity[0])),reverse = True, key = lambda x: x[1])

[(0, 1.0000000000000002),
 (1216, 0.29986532511593345),
 (2409, 0.28644594961577313),
 (507, 0.2710098294963041),
 (539, 0.2706659809803833),
 (1204, 0.2625754538144587),
 (582, 0.26148818018424536),
 (3730, 0.25715142542972574),
 (1194, 0.25620504608813943),
 (778, 0.2491009475118111),
 (61, 0.24653342054454624),
 (1920, 0.24419314525275215),
 (2786, 0.24209101306752093),
 (4048, 0.24198875709123052),
 (4405, 0.24019223070763068),
 (972, 0.2338821384818744),
 (322, 0.23076923076923075),
 (4192, 0.22880215766121476),
 (2333, 0.22205779584216376),
 (3608, 0.2201762114819948),
 (74, 0.21995293510729183),
 (577, 0.21969401455243587),
 (973, 0.2196940145524358),
 (1089, 0.21757131728816842),
 (3675, 0.21726204731337043),
 (495, 0.21571674297647797),
 (1201, 0.21571674297647797),
 (3327, 0.21483446221182984),
 (47, 0.21204880838762138),
 (94, 0.21182963643408081),
 (172, 0.20965696734438366),
 (2999, 0.20965696734438366),
 (260, 0.2081453617075184),
 (1275, 0.20814536170751838),
 (1329, 0.20814536170751838),
 (4, 0.2080125735844609),
 (2971, 0.20758412292650924),
 (305, 0.20672455764868072),
 (151, 0.20483662259967564),
 (1321, 0.20483662259967564),
 (3999, 0.2046468711716401),
 (27, 0.20336295869552104),
 (220, 0.20131905799006777),
 (373, 0.20033416898825337),
 (1444, 0.20016019225635892),
 (1071, 0.2000625293121421),
 (931, 0.19814848097530424),
 (83, 0.19795764159656265),
 (168, 0.1976664844429603),
 (184, 0.19535451620220173),
 (2204, 0.19535451620220173),
 (4336, 0.19535451620220173),
 (1982, 0.19223226273338134),
 (300, 0.19096396641051544),
 (3538, 0.19096396641051544),
 (36, 0.1909639664105154),
 (91, 0.18946618668626833),
 (942, 0.18887686585995425),
 (3162, 0.18762218965128746),
 (1831, 0.18685673434682068),
 (31, 0.1849000654084097),
 (41, 0.1849000654084097),
 (2515, 0.1849000654084097),
 (67, 0.18427434427242975),
 (661, 0.18302666282596894),
 (2731, 0.1815682598006407),
 (1537, 0.18116432546313532),
 (150, 0.17902871850985821),
 (342, 0.17576348305930709),
 (26, 0.17505471314812435),
 (466, 0.17471413945365305),
 (1383, 0.17295817388759027),
 (2075, 0.17255919256291524),
 (4348, 0.17118419700436519),
 (149, 0.17103344030668952),
 (311, 0.17093520167692652),
 (1344, 0.17093520167692652),
 (111, 0.1709352016769265),
 (490, 0.1706971854997297),
 (1488, 0.1706971854997297),
 (838, 0.16984155512168936),
 (581, 0.16984155512168933),
 (275, 0.16724840200141816),
 (3354, 0.16724840200141816),
 (7, 0.167093470609201),
 (52, 0.167093470609201),
 (56, 0.16694514082354447),
 (249, 0.16694514082354447),
 (108, 0.16526725762745997),
 (529, 0.16526725762745997),
 (1297, 0.16526725762745997),
 (461, 0.1647705109143269),
 (413, 0.16477051091432687),
 (2760, 0.16401847362094593),
 (1355, 0.1634996425534681),
 (1938, 0.16349964255346808),
 (476, 0.1634301126151534),
 (505, 0.1634301126151534),
 (46, 0.16239958858823),
 (3409, 0.16239958858823),
 (1273, 0.16178755723235852),
 (1056, 0.1617875572323585),
 (1396, 0.1613940087116806),
 (1479, 0.1613940087116806),
 (127, 0.1611258466588724),
 (1373, 0.16012815380508716),
 (2378, 0.16012815380508716),
 (72, 0.16012815380508713),
 (859, 0.16012815380508713),
 (2169, 0.16012815380508713),
 (95, 0.1601281538050871),
 (595, 0.1585187847802434),
 (1808, 0.15794943794779692),
 (1178, 0.15585730003983933),
 (1560, 0.15585730003983933),
 (1965, 0.15534712747612348),
 (4010, 0.15534712747612348),
 (487, 0.15408338784034142),
 (2970, 0.15408338784034142),
 (187, 0.15384615384615383),
 (4079, 0.15384615384615383),
 (158, 0.15253477177414312),
 (502, 0.15253477177414312),
 (483, 0.1513068831672006),
 (1096, 0.1513068831672006),
 (1158, 0.1513068831672006),
 (1322, 0.15097027121927944),
 (1715, 0.15097027121927944),
 (14, 0.15004689698410661),
 (1086, 0.1500468969841066),
 (4230, 0.1500468969841066),
 (2133, 0.14978617237881955),
 (3376, 0.14867525836251314),
 (2873, 0.147180996735913),
 (513, 0.14651588715165131),
 (754, 0.14651588715165131),
 (166, 0.1465158871516513),
 (2450, 0.1465158871516513),
 (3628, 0.1465158871516513),
 (68, 0.14617633655117152),
 (1004, 0.14617633655117152),
 (1274, 0.14617633655117152),
 (1658, 0.14617633655117152),
 (3634, 0.14484136487558028),
 (579, 0.1437993271357627),
 (1047, 0.1437993271357627),
 (1833, 0.1437993271357627),
 (4673, 0.1437993271357627),
 (1741, 0.14351616441832768),
 (256, 0.14322297480788657),
 (1299, 0.14322297480788657),
 (102, 0.14235407108686474),
 (28, 0.14153462926807445),
 (122, 0.14153462926807445),
 (294, 0.14153462926807445),
 (422, 0.14153462926807445),
 (549, 0.1401425507601155),
 (870, 0.1401425507601155),
 (900, 0.1401425507601155),
 (1878, 0.14011213457945124),
 (200, 0.13977131156292244),
 (1524, 0.13977131156292244),
 (1575, 0.13977131156292244),
 (2496, 0.13937366833451514),
 (568, 0.13937366833451512),
 (17, 0.13797289239745258),
 (182, 0.13725270326150324),
 (278, 0.13725270326150324),
 (1617, 0.13725270326150324),
 (1002, 0.13693937303317935),
 (1327, 0.13655774839978377),
 (1501, 0.13655774839978377),
 (2161, 0.13655774839978377),
 (3781, 0.13655774839978377),
 (454, 0.1358732440973515),
 (2547, 0.1358732440973515),
 (87, 0.13533299049019168),
 (232, 0.13533299049019168),
 (1220, 0.1345345587992625),
 (4538, 0.1345345587992625),
 (233, 0.13355611265883557),
 (668, 0.13355611265883557),
 (935, 0.13355611265883557),
 (2323, 0.13355611265883557),
 (3982, 0.13355611265883557),
 (449, 0.13344012817090595),
 (843, 0.13344012817090595),
 (1031, 0.13344012817090595),
 (3498, 0.13344012817090595),
 (1418, 0.13323467750529824),
 (1497, 0.1320989873168695),
 (420, 0.1319717610643751),
 (777, 0.1319717610643751),
 (126, 0.1316245316231641),
 (1280, 0.1307440900921227),
 (2584, 0.1307440900921227),
 (3663, 0.1307440900921227),
 (3954, 0.1307440900921227),
 (1512, 0.13074409009212268),
 (3309, 0.13074409009212268),
 (228, 0.12955005512625914),
 (123, 0.1283881477532739),
 (2480, 0.1283881477532739),
 (2796, 0.1283881477532739),
 (2856, 0.1283881477532739),
 (1015, 0.1282051282051282),
 (2072, 0.1282051282051282),
 (2181, 0.1282051282051282),
 (3622, 0.1282051282051282),
 (85, 0.12810252304406974),
 (35, 0.12810252304406972),
 (134, 0.12810252304406972),
 (319, 0.12810252304406972),
 (368, 0.12810252304406972),
 (1774, 0.12810252304406972),
 (2053, 0.12810252304406972),
 (4018, 0.12810252304406972),
 (4198, 0.12810252304406972),
 (4490, 0.12810252304406972),
 (740, 0.12725695259515554),
 (3093, 0.12725695259515554),
 (238, 0.12691660175143157),
 (138, 0.12659242088545833),
 (223, 0.12659242088545833),
 (814, 0.12659242088545833),
 (1195, 0.12659242088545833),
 (2686, 0.12659242088545833),
 (1574, 0.1261107739106075),
 (3212, 0.12580855934939952),
 (33, 0.12561485860426555),
 (773, 0.12561485860426555),
 (1156, 0.12561485860426555),
 (1942, 0.12561485860426555),
 (4256, 0.12561485860426555),
 (4403, 0.12561485860426555),
 (369, 0.12503908082008885),
 (10, 0.12503908082008883),
 (937, 0.12503908082008883),
 (1082, 0.12503908082008883),
 (3755, 0.12503908082008883),
 (1496, 0.12403473458920845),
 (541, 0.12403473458920844),
 (229, 0.12378237474570461),
 (508, 0.1235415527768502),
 (362, 0.12326671027227314),
 (2498, 0.12301385521570944),
 (939, 0.12229989761755714),
 (1037, 0.12209657262637608),
 (1614, 0.12209657262637608),
 (84, 0.12201777521731262),
 (654, 0.12201777521731262),
 (2439, 0.12201777521731262),
 (208, 0.12104550653376048),
 (920, 0.12104550653376048),
 (1474, 0.12104550653376048),
 (2645, 0.12104550653376048),
 (2652, 0.12104550653376048),
 (4331, 0.12104550653376048),
 (266, 0.1207011373963169),
 (438, 0.1207011373963169),
 (510, 0.1207011373963169),
 (557, 0.1207011373963169),
 (3935, 0.1207011373963169),
 (2331, 0.12009611535381534),
 (2674, 0.12009611535381534),
 (3083, 0.12009611535381534),
 (3218, 0.12009611535381534),
 (4737, 0.12009611535381534),
 (410, 0.11935247900657214),
 (480, 0.11935247900657214),
 (1401, 0.11935247900657214),
 (139, 0.11916871834484359),
 (511, 0.11894020669001051),
 (781, 0.11894020669001051),
 (980, 0.11894020669001051),
 (1756, 0.11894020669001051),
 (2093, 0.11894020669001051),
 (3736, 0.11894020669001051),
 (1405, 0.1182624791978165),
 (3235, 0.11804804116247142),
 (334, 0.1180480411624714),
 (400, 0.11694106924093722),
 (1306, 0.11694106924093722),
 (2060, 0.11694106924093722),
 (2741, 0.11694106924093722),
 (371, 0.11678545896676293),
 (412, 0.11678545896676293),
 (2241, 0.11678545896676293),
 (1673, 0.11651034560709261),
 (2789, 0.11651034560709261),
 (4000, 0.11651034560709261),
 (4654, 0.11651034560709261),
 (363, 0.1165103456070926),
 (3721, 0.1165103456070926),
 (160, 0.11561170597113389),
 (587, 0.11556254088025608),
 (2284, 0.11556254088025608),
 (564, 0.11503946170861017),
 (678, 0.11503946170861017),
 (2660, 0.11503946170861017),
 (589, 0.11483385035264292),
 (2488, 0.11437725271791938),
 (2820, 0.11437725271791938),
 (189, 0.11322770341445959),
 (3006, 0.11322770341445959),
 (279, 0.11322770341445958),
 (432, 0.11322770341445958),
 (473, 0.11322770341445958),
 (813, 0.11322770341445958),
 (236, 0.11322770341445956),
 (960, 0.11322770341445956),
 (1301, 0.11322770341445956),
 (4545, 0.11244949691847501),
 (1233, 0.11211213233271873),
 (18, 0.11168711865749101),
 (50, 0.11149893466761211),
 (775, 0.11149893466761211),
 (1616, 0.11149893466761211),
 (2583, 0.11149893466761211),
 (536, 0.11102889792108189),
 (43, 0.11102889792108188),
 (997, 0.11102889792108188),
 (889, 0.11098534863604863),
 (3147, 0.11094003924504581),
 (808, 0.11020775375559674),
 (850, 0.11020775375559674),
 (1005, 0.11020775375559674),
 (1348, 0.11020775375559674),
 (4165, 0.11020775375559674),
 (4473, 0.11020775375559674),
 (2372, 0.10997646755364592),
 (3443, 0.10997646755364592),
 (121, 0.10984700727621793),
 (1589, 0.10984700727621793),
 (4468, 0.10984700727621793),
 (206, 0.10948978029027179),
 (81, 0.10878565864408421),
 (301, 0.10878565864408421),
 (3428, 0.10826639239215335),
 (21, 0.10826639239215334),
 (203, 0.10826639239215334),
 (1945, 0.10826639239215334),
 (3008, 0.10826639239215334),
 (230, 0.108094949066235),
 (799, 0.108094949066235),
 (169, 0.10795837927188262),
 (270, 0.10795837927188262),
 (618, 0.10795837927188262),
 (692, 0.10795837927188262),
 (3553, 0.10795837927188262),
 (239, 0.10741723110591492),
 (627, 0.10741723110591492),
 (653, 0.10741723110591492),
 (2326, 0.10741723110591492),
 (307, 0.10736246830291345),
 (5, 0.10699012312772824),
 (752, 0.10699012312772824),
 (1832, 0.10699012312772824),
 (3630, 0.10699012312772824),
 (39, 0.10675210253672475),
 (626, 0.10675210253672475),
 (786, 0.10675210253672475),
 (4777, 0.10675210253672475),
 (3556, 0.10604746049596296),
 (572, 0.10604746049596295),
 (242, 0.10529962529853128),
 (306, 0.10529962529853128),
 (332, 0.10529962529853128),
 (472, 0.10529962529853128),
 (1237, 0.10529962529853128),
 (2644, 0.10529962529853128),
 (3926, 0.10529962529853128),
 (4626, 0.10529962529853128),
 (170, 0.105129283382795),
 (262, 0.105129283382795),
 (1019, 0.105129283382795),
 (1166, 0.10482848367219183),
 (1745, 0.10482848367219183),
 (2381, 0.10482848367219183),
 (2634, 0.10482848367219183),
 (4135, 0.10482848367219183),
 (4431, 0.10482848367219183),
 (467, 0.10423454980627081),
 (131, 0.10390486669322622),
 (295, 0.10390486669322622),
 (854, 0.10390486669322622),
 (3340, 0.10390486669322622),
 (1639, 0.10336227882434038),
 (2448, 0.10300524052492097),
 (16, 0.10256410256410256),
 (75, 0.10256410256410256),
 (687, 0.10256410256410256),
 (1771, 0.10256410256410256),
 (2148, 0.10256410256410256),
 (2817, 0.10256410256410256),
 (105, 0.10241831129983783),
 (2456, 0.10241831129983783),
 (2521, 0.10241831129983783),
 (3621, 0.10241831129983783),
 (3055, 0.10241831129983782),
 (3839, 0.10241831129983782),
 (1455, 0.10168147934776052),
 (3905, 0.10168147934776052),
 (174, 0.10127393670836667),
 (922, 0.10127393670836667),
 (1113, 0.10127393670836667),
 (2938, 0.10127393670836667),
 (3028, 0.10127393670836667),
 (3152, 0.10127393670836667),
 (3874, 0.10127393670836667),
 (4097, 0.10127393670836667),
 (2106, 0.10087125544480038),
 (325, 0.10016708449412667),
 (624, 0.10016708449412667),
 (2762, 0.10016708449412667),
 (3891, 0.10016708449412667),
 (45, 0.10008009612817946),
 (3441, 0.10008009612817945),
 (96, 0.10003126465607107),
 (101, 0.10003126465607107),
 (207, 0.10003126465607107),
 (312, 0.10003126465607107),
 (632, 0.10003126465607107),
 (1289, 0.10003126465607107),
 (1294, 0.10003126465607107),
 (2247, 0.10003126465607107),
 (1439, 0.09930726528736966),
 (2099, 0.09930726528736966),
 (70, 0.09883324222148016),
 (82, 0.09883324222148016),
 (330, 0.09883324222148016),
 (643, 0.09883324222148016),
 (988, 0.09883324222148016),
 (1523, 0.09883324222148016),
 (2916, 0.09883324222148016),
 (4558, 0.09883324222148016),
 (2386, 0.09805806756909204),
 (157, 0.09805806756909202),
 (715, 0.09805806756909202),
 (1077, 0.09805806756909202),
 (1884, 0.09805806756909202),
 (4472, 0.09805806756909202),
 (51, 0.09781383788084239),
 (222, 0.09781383788084239),
 (491, 0.09781383788084239),
 (365, 0.09767725810110087),
 (445, 0.09767725810110087),
 (2163, 0.09767725810110087),
 (3620, 0.09767725810110087),
 (3783, 0.09767725810110087),
 (4045, 0.09767725810110087),
 (1775, 0.09709195467257717),
 (535, 0.09656090991705352),
 (898, 0.09656090991705352),
 (1109, 0.09656090991705352),
 (1823, 0.09656090991705352),
 (2253, 0.09656090991705352),
 (2395, 0.09656090991705352),
 (148, 0.09607689228305229),
 (263, 0.09607689228305229),
 (878, 0.09607689228305229),
 (1721, 0.09607689228305229),
 (1727, 0.09607689228305229),
 (2259, 0.09607689228305229),
 (2787, 0.09607689228305229),
 (3994, 0.09607689228305229),
 (9, 0.09548198320525772),
 (908, 0.09548198320525772),
 (1623, 0.09548198320525772),
 (2021, 0.09548198320525772),
 (3022, 0.09548198320525772),
 (3560, 0.09501857794816083),
 (634, 0.09443843292997713),
 (728, 0.09443843292997713),
 (979, 0.09443843292997713),
 (1996, 0.09443843292997713),
 (2556, 0.09443843292997713),
 (791, 0.09421114395319916),
 (2268, 0.09421114395319916),
 (2270, 0.09421114395319916),
 (2562, 0.09421114395319916),
 (3572, 0.09421114395319916),
 (3901, 0.09421114395319916),
 (4203, 0.09421114395319916),
 (11, 0.09342836717341034),
 (76, 0.09342836717341034),
 (1168, 0.09342836717341034),
 (2701, 0.09342836717341034),
 (3464, 0.09342836717341034),
 (4083, 0.09342836717341034),
 (193, 0.09288103752413637),
 (93, 0.09245003270420486),
 (271, 0.09245003270420486),
 (674, 0.09245003270420486),
 (1276, 0.09245003270420486),
 (1357, 0.09245003270420486),
 (1692, 0.09245003270420486),
 (2592, 0.09245003270420486),
 (2650, 0.09245003270420486),
 (2831, 0.09245003270420486),
 (3720, 0.09245003270420486),
 (4502, 0.09245003270420486),
 (660, 0.09245003270420485),
 (1262, 0.09245003270420485),
 (1365, 0.09245003270420485),
 (1573, 0.09245003270420485),
 (1686, 0.09245003270420485),
 (2396, 0.09245003270420485),
 (3537, 0.09245003270420485),
 (129, 0.0915018021743355),
 (243, 0.0915018021743355),
 (596, 0.0915018021743355),
 (1446, 0.0915018021743355),
 (1632, 0.0915018021743355),
 (1701, 0.0915018021743355),
 (3407, 0.0915018021743355),
 (785, 0.09124148357522649),
 (219, 0.09078412990032037),
 (244, 0.09078412990032037),
 (1944, 0.09078412990032037),
 (2651, 0.09078412990032037),
 (1990, 0.09065471553673685),
 (3431, 0.09065471553673685),
 (97, 0.09058216273156766),
 (782, 0.09058216273156766),
 (3300, 0.09058216273156766),
 (2570, 0.09007912422186248),
 (419, 0.08968970586617499),
 (602, 0.08968970586617499),
 (732, 0.08968970586617499),
 (1278, 0.08968970586617499),
 (1846, 0.08968970586617499),
 (3881, 0.08968970586617499),
 (12, 0.08920515501750789),
 (88, 0.08920515501750789),
 (167, 0.08920515501750789),
 (356, 0.08920515501750789),
 (1347, 0.08920515501750789),
 (1480, 0.08920515501750789),
 (2090, 0.08920515501750789),
 (2251, 0.08920515501750789),
 (2957, 0.08920515501750789),
 (4566, 0.08920515501750789),
 (59, 0.08896008544727063),
 (331, 0.0888231183368655),
 (2363, 0.0888231183368655),
 (2850, 0.0888231183368655),
 (3389, 0.0888231183368655),
 (3462, 0.0888231183368655),
 (4123, 0.0888231183368655),
 (4343, 0.0888231183368655),
 (4353, 0.0888231183368655),
 (274, 0.08861469461982083),
 (1906, 0.08798117404291673),
 (2109, 0.08798117404291673),
 (3910, 0.08798117404291673),
 (2115, 0.08788174152965353),
 (292, 0.08770580193070292),
 (358, 0.08770580193070292),
 (1027, 0.08770580193070292),
 (1312, 0.08770580193070292),
 (1434, 0.08770580193070292),
 (1631, 0.08770580193070292),
 (2868, 0.08770580193070292),
 (3322, 0.08770580193070292),
 (735, 0.08716272672808179),
 (1783, 0.08716272672808179),
 (2713, 0.08716272672808179),
 (2740, 0.08716272672808179),
 (125, 0.08699848552934203),
 (479, 0.08684168428648435),
 (2763, 0.08684168428648435),
 (143, 0.0863667034175061),
 (212, 0.0863667034175061),
 (1018, 0.0863667034175061),
 (2596, 0.0863667034175061),
 (183, 0.08633531446374632),
 (23, 0.08627959628145762),
 (141, 0.08627959628145762),
 (389, 0.08627959628145762),
 (745, 0.08627959628145762),
 (794, 0.08627959628145762),
 (1073, 0.08627959628145762),
 (1249, 0.08627959628145762),
 (1259, 0.08627959628145762),
 (1364, 0.08627959628145762),
 (3448, 0.08627959628145762),
 (3449, 0.08627959628145762),
 (199, 0.08559209850218259),
 (827, 0.08559209850218259),
 (1530, 0.08559209850218259),
 (2003, 0.08559209850218259),
 (2135, 0.08559209850218259),
 (2880, 0.08559209850218259),
 (3154, 0.08559209850218259),
 (3390, 0.08559209850218259),
 (4516, 0.08559209850218259),
 (4587, 0.08559209850218259),
 (2, 0.08492077756084468),
 (142, 0.08492077756084468),
 (457, 0.08492077756084468),
 (1378, 0.08492077756084468),
 (3135, 0.08492077756084468),
 (3365, 0.08492077756084468),
 (3515, 0.08492077756084468),
 (4754, 0.08492077756084468),
 (4790, 0.08492077756084468),
 (234, 0.08483796839677037),
 (2052, 0.08483796839677037),
 (2354, 0.08483796839677037),
 (2968, 0.08483796839677037),
 (32, 0.084103426706236),
 (217, 0.084103426706236),
 (1011, 0.084103426706236),
 (441, 0.08362420100070908),
 (894, 0.08362420100070908),
 (1142, 0.08362420100070908),
 (1688, 0.08362420100070908),
 (2304, 0.08362420100070908),
 (4259, 0.08362420100070908),
 (4560, 0.08362420100070908),
 (1097, 0.08362420100070907),
 (48, 0.08338763984501665),
 (190, 0.08338763984501665),
 (1305, 0.08338763984501665),
 (2264, 0.08338763984501665),
 (62, 0.0826898230594723),
 (381, 0.0826898230594723),
 (534, 0.0826898230594723),
 (1698, 0.0826898230594723),
 (3180, 0.0826898230594723),
 (3978, 0.0826898230594723),
 (4568, 0.0826898230594723),
 (1, 0.08238525545716345),
 (152, 0.08238525545716345),
 (315, 0.08238525545716345),
 (366, 0.08238525545716345),
 (547, 0.08238525545716345),
 (1241, 0.08238525545716345),
 (2128, 0.08238525545716345),
 (19, 0.08200923681047297),
 (403, 0.08200923681047297),
 (79, 0.08134518347820842),
 (2203, 0.08134518347820842),
 (227, 0.081199794294115),
 (341, 0.081199794294115),
 (787, 0.081199794294115),
 (1032, 0.081199794294115),
 (1207, 0.081199794294115),
 (1749, 0.081199794294115),
 (1768, 0.081199794294115),
 (2167, 0.081199794294115),
 (2636, 0.081199794294115),
 (2661, 0.081199794294115),
 (3137, 0.081199794294115),
 (3140, 0.081199794294115),
 (3301, 0.081199794294115),
 (3470, 0.081199794294115),
 (63, 0.0806970043558403),
 (501, 0.0806970043558403),
 (2888, 0.0806970043558403),
 (38, 0.08006407690254357),
 (245, 0.08006407690254357),
 (375, 0.08006407690254357),
 (584, 0.08006407690254357),
 (812, 0.08006407690254357),
 (866, 0.08006407690254357),
 (901, 0.08006407690254357),
 (1519, 0.08006407690254357),
 (1664, 0.08006407690254357),
 (2339, 0.08006407690254357),
 (2671, 0.08006407690254357),
 (2865, 0.08006407690254357),
 (2877, 0.08006407690254357),
 (3527, 0.08006407690254357),
 (4075, 0.08006407690254357),
 (4492, 0.08006407690254357),
 (4641, 0.08006407690254357),
 (4657, 0.08006407690254357),
 (224, 0.07944581222989573),
 (768, 0.07944581222989573),
 (37, 0.07897471897389846),
 (164, 0.07897471897389846),
 (899, 0.07897471897389846),

In [38]:

        
def recomended_movies(movie):
    movie_index = new_movies[new_movies['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda x: x[1])
    
    for i in distances[1:6]:  # Skip the first item since it's the movie itself
        print(new_movies.iloc[i[0]].title)

In [39]:
recomended_movies('Spectre')

Quantum of Solace
Skyfall
Never Say Never Again
From Russia with Love
Octopussy

In [40]:
import pickle

In [41]:
pickle.dump(new_movies,open("movies_list.pkl", "wb"))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [42]:
movies_dict = new_movies['title'].values
movies_dict

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [43]:
pickle.dump(movies_dict, open('Movies_dict.pkl', "wb"))

In [44]:
list(movies_dict).index('Avatar')

0

In [45]:
movies_dict[1]

"Pirates of the Caribbean: At World's End"

In [46]:
def recomended_movies(movie):
    movie_index = list(movies_dict).index(movie)
    movies_list = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda x: x[1])

    Movies = []
    for i in movies_list[1:6]:  # Skip the first item since it's the movie itself
        Movies.append(movies_dict[i])
    return Movies

In [47]:
for i in movies_list[1:6]:
    print(movies_dict[i[0]])

NameError: name 'movies_list' is not defined

In [ ]:
movie_index = list(movies_dict).index('Aliens')
movies_list = sorted(list(enumerate(similarity[movie_index])), reverse=True, key=lambda x: x[1])

    
for i in movies_list[1:6]:
    print(i[0])